### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by ilearnio** [ermanc/ChromeiQL#1]
I have just installed the Chrome plugin but it seems like it's not working. When the page loads it sends a Graphql request to the endpoint that I have specified, but not with the query that I typed (it uses some other query, don't know where it gets it from). And I also can't fire the query again, probably because of the JS error.

Screenshots:
http://take.ms/smKc9
http://take.ms/3MMbo

**Comment by ilearnio** [comment]
My fault... There is something wrong with my endpoint. Sorry for disturbing

**Comment by ermanc** [comment]
@ilearnio No worries. The first query it sends is the introspection query which it then uses to autocomplete the fields, check the types, give descriptions etc. 

Seems like your server hasn't responded to that initial query correctly, like you said. Glad you got it figured out.
