### ISSUE TITLE
Relaunching extension triggers duplicate request to endpoint.

### ISSUE THREAD

**Issue by prasad83** [ermanc/ChromeiQL#10]
When the extension is re-opened two request are sent to the endpoint on-load.

This is likely due to initialization of GraphiQL fetcher property.
```
<GraphiQL...
fetcher = {graphQLFetcher(endpoint)}
```

Attempt to fetch only when currentEndpoint is set would avoid this.

```
<GraphiQL...
fetcher = {...this.state.currentEndpoint ? graphQLFetcher(endpoint) : function(){}}
```

**Comment by ermanc** [comment]
#11 addresses this issue. Seems to be working well locally. Will add to a release soon.
