### ISSUE TITLE
Update graphiql version

### ISSUE THREAD

**Issue by vladar** [ermanc/ChromeiQL#3]
Hey, thanks for this plugin. Can you update graphiql version? Newer version has "prettify" feature.

**Comment by pupeno** [comment]
This issue that was solved a year ago in GraphiQL is making ChromeiQL unusable for me: https://github.com/graphql/graphiql/issues/142

I would very much appreciate an upgrade.

**Comment by ermanc** [comment]
@vladar @pupeno Thanks for reminding me. I have a working build with the newer GraphiQL version that I've been playing around locally with our graphql server. Seems stable _and_ compatible enough. Prepping for release soon.

**Comment by PowerKiKi** [comment]
Is there anything we could do to help get that new version released ?

**Comment by ermanc** [comment]
@vladar @pupeno @PowerKiKi I've just upgraded GraphiQL to the current latest 0.11.3 with prettify, query history, better editor/highlighting support and a way more efficient results pane.
