### ISSUE TITLE
Chromeiql stringifies variables before sending them in a request

### ISSUE THREAD

**Issue by bryan-havenly** [ermanc/ChromeiQL#7]
This extension is setting `variables` to a string before the entire request payload is stringified, instead of sending an object which is more standard.

**Comment by ermanc** [comment]
@bryan-havenly yes, but that's because graphql/graphiql standard used to be that way at the time. see: https://github.com/graphql/graphiql/pull/168

that said, once I update graphiql to latest, `variables` will be an object payload, not stringified JSON.

**Comment by bryan-havenly** [comment]
I have a PR to do that right now, if you want to merge it. If you'd prefer to do it as part of a larger update that's fine.

**Comment by ermanc** [comment]
Thanks for the PR @bryan-havenly. I'll hold on to that for now, since I do have a local version that I've been sitting on for too long. I suspect just getting that out is simpler but I might just merge yours too, if that's not the case.

**Comment by bryan-havenly** [comment]
That's fine with me as well. I just always try to submit a PR at the same time as an issue if possible :)

We just started using graphql at my work and so far this extension has been awesome. Thanks for making it.
